--1
SELECT CITY, STATE
FROM STATION;

--2
SELECT 
    ROUND(SUM(LAT_N), 2) AS lat,
    ROUND(SUM(LONG_W), 2) AS lon
FROM 
    STATION;

--3
SELECT DISTINCT CITY
FROM STATION
WHERE MOD(ID, 2) = 0;

--4
SELECT 
    COUNT(CITY) - COUNT(DISTINCT CITY) AS difference
FROM 
    STATION;

--5
SELECT CITY, LENGTH(CITY) AS length
FROM STATION
ORDER BY LENGTH(CITY) ASC, CITY ASC
LIMIT 1;

SELECT CITY, LENGTH(CITY) AS length
FROM STATION
ORDER BY LENGTH(CITY) DESC, CITY ASC
LIMIT 1;

--6
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '^[aeiouAEIOU]';

--7
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '[aeiouAEIOU]$';

--8
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '^[aeiouAEIOU].*[aeiouAEIOU]$';

--9
SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT REGEXP '^[aeiouAEIOU]';

--10
SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT REGEXP '[aeiouAEIOU]$';

--11
SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT REGEXP '^[aeiouAEIOU]' OR CITY NOT REGEXP '[aeiouAEIOU]$';

--12
SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT REGEXP '^[aeiouAEIOU]' AND CITY NOT REGEXP '[aeiouAEIOU]$';

--13
SELECT TRUNCATE(SUM(LAT_N), 4) AS sum_lat
FROM STATION
WHERE LAT_N > 38.7880 AND LAT_N < 137.2345;

--14
SELECT TRUNCATE(MAX(LAT_N), 4) AS max_lat
FROM STATION
WHERE LAT_N < 137.2345;

--15
SELECT ROUND(LONG_W, 4) AS long_w
FROM STATION
WHERE LAT_N = (SELECT MAX(LAT_N) FROM STATION WHERE LAT_N < 137.2345);

--16
SELECT ROUND(MIN(LAT_N), 4) AS min_lat
FROM STATION
WHERE LAT_N > 38.7780;

--17
SELECT ROUND(LONG_W, 4) AS long_w
FROM STATION
WHERE LAT_N = (SELECT MIN(LAT_N) FROM STATION WHERE LAT_N > 38.7780);

--18
SELECT ROUND(
            ABS((SELECT MIN(LAT_N) FROM STATION) - (SELECT MAX(LAT_N) FROM STATION)) +
            ABS((SELECT MIN(LONG_W) FROM STATION) - (SELECT MAX(LONG_W) FROM STATION)), 4
          ) AS manhattan_distance
FROM dual;

--19
SELECT ROUND(
            SQRT(POW((SELECT MAX(LAT_N) FROM STATION) - (SELECT MIN(LAT_N) FROM STATION), 2) + 
                 POW((SELECT MAX(LONG_W) FROM STATION) - (SELECT MIN(LONG_W) FROM STATION), 2)), 4
          ) AS euclidean_distance
FROM dual;

--20
WITH ordered_lats AS (
    SELECT LAT_N,
           ROW_NUMBER() OVER (ORDER BY LAT_N) AS row_num,
           COUNT(*) OVER () AS total_count
    FROM STATION
)
SELECT ROUND(
    AVG(LAT_N), 4) as median_lat
FROM ordered_lats
WHERE row_num IN ((total_count + 1) DIV 2, (total_count + 2) DIV 2);
